Feature/support for vendor prefix
PentiaLabs/generator-helix pull request #70
Opened 2017-02-22 16:29 UTC by saberone

### Requirements

### Description of the Change

I added the option to add a "vendorprefix" to the projectname in Visual Studio and the unicorn folders.

The generator now also prompts for a vendorprefix and the LayerPrefixedProjectName will contain the prefix if it's not empty.

### Benefits

### WORLD DOMINATION

But seriously, it's makes it possible to have a better organised folder structure.

### Possible Drawbacks

Users are being asked an additional question.

2017-02-22 17:00 UTC, Saturate requested changes
Thanks for the PR :-) However I have two minor issues:

If you don't define the optional Vendor Prefix, it will create the files as following:

`src\Feature\FeatureName\code\Feature..FeatureName.csproj`

Where there is an extra `.`

Another thing is that the Vendor Prefix needs to be the first (`VendorPrefix.Layer.Name`) in the file name, like documented on http://helix.sitecore.net/principles/visual-studio/projects.html#projects

PS. If you merge the master into your branch you will have some more tests. You could write a test for your addition and it's perfect!

2017-02-23 13:39 UTC, Saturate approved these changes
Awesome! The tests is a really nice touch, I also tested it manually. It works like one would expect.

I would say this is ready to merge. But I'll let another one review, and merge.

(PS I would suggest to the merger to do a squash to keep our git history clean. The author could also do this.)

2017-02-23 13:47 UTC, saberone commented
I agree with the squashing. What I find a bit strange, is that Github doesn't let the PR author write a squash suggestion as part of the PR.

2017-02-23 15:09 UTC, istern approved these changes

2017-02-27 08:28 UTC, merged